# define your own db
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smallestdb?characterEncoding=utf8
    username: root
    password: fengxiang